INSERT INTO leads (slug, business_name, business_type, category, description_short, phone, email, website, address, city, country, rating, reviews_count, place_id, google_url, logo_url, hero_url, images, status, notes, contact_method, contact_date, brief_data, problem, problem_key) VALUES ('zambrano-asociados-immigration-and-real-estate-lawyer-in-ecuador', 'Zambrano & Asociados (Immigration and Real Estate Lawyer in Ecuador)', 'Servicios legales', '', '', '+593 98 922 8640', '', 'http://www.zambranoyasociados.com/', 'Edificio Cevallos & Cevallos, Segunda Planta, Of. 2A, Av. Manabí, entre Av América y, Paulo Emilio Macias, 130102 Portoviejo, Ecuador', 'Portoviejo', 'Ecuador', '5.0', '20', 'ChIJcbeIXkyNK5ARCUSiNwJRDR4', 'https://www.google.com/maps/search/Zambrano%20%26%20Asociados%20%28Immigration%20and%20Real%20Estate%20Lawyer%20in%20Ecuador%29%20Portoviejo', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkJqPBjZWKXo8dtLLAcAfK9g-Xo-Yoc8n4YUgRGpPicnMoT4co7QdCECO7nPWkaJ9UnuNgzZAfEbH_dYGDsDKXXiRDMgMQcTF-samBjGi_QRDcQ6gjswTBC5Qdk8vzXBKRO3ZxiZA=w1000-h1000-c-n', '', '[]', 'contacted', '', '', '', '{}', '', '') ON CONFLICT (slug) DO NOTHING;

INSERT INTO leads (slug, business_name, business_type, category, description_short, phone, email, website, address, city, country, rating, reviews_count, place_id, google_url, logo_url, hero_url, images, status, notes, contact_method, contact_date, brief_data, problem, problem_key) VALUES ('abogados-ok', 'Abogados Ok', 'Servicio de búsqueda de abogado', '', '', '+593 99 951 2081', '', '', 'XG4G+W7X, Cdla. Los Mangos: Luis Dueñas Vera y, Manuel Andrade Ureta, 130102 Portoviejo, Ecuador', 'Portoviejo', 'Ecuador', '5.0', '1', 'ChIJa7iZS6jtK5AR84I0Gxw4BPc', 'https://www.google.com/maps/search/Abogados%20Ok%20Portoviejo', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=WC27n1r2nA_USvJhuwb9Kw&cb_client=search.gws-prod.gps&w=80&h=92&yaw=211.65454&pitch=0&thumbfov=100', '', '[]', 'scraped', '', '', '', '{}', '', '') ON CONFLICT (slug) DO NOTHING;

INSERT INTO leads (slug, business_name, business_type, category, description_short, phone, email, website, address, city, country, rating, reviews_count, place_id, google_url, logo_url, hero_url, images, status, notes, contact_method, contact_date, brief_data, problem, problem_key) VALUES ('atlas-grupo-juridico', 'ATLAS GRUPO JURIDICO', 'Bufete', '', '', '+593 99 486 9892', '', '', 'Portoviejo, Ecuador', 'Portoviejo', 'Ecuador', '5.0', '46', 'ChIJBUgNxrONK5ARlO8xrPhNt5g', 'https://www.google.com/maps/search/ATLAS%20GRUPO%20JURIDICO%20Portoviejo', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWlXdoofQCiWKkmtzY8W9zTr86rHJQKHp5o9eWYxj4PQN6F5fdZtxEOIatF7sjd0Jz8b4nECw0HfDXIDdmB1JwW-gfUfWsgdzvyDEeLtkdbMrAjpaxl421oMBNnNNMkk5H86Pu-zneFs8ZCG=w1000-h1000-c-n', '', '[]', 'scraped', '', '', '', '{}', '', '') ON CONFLICT (slug) DO NOTHING;

INSERT INTO leads (slug, business_name, business_type, category, description_short, phone, email, website, address, city, country, rating, reviews_count, place_id, google_url, logo_url, hero_url, images, status, notes, contact_method, contact_date, brief_data, problem, problem_key) VALUES ('estudio-jurídico-cabrera-pita-abogados', 'Estudio Jurídico Cabrera Pita &Abogados', 'Servicios legales', '', '', '+593 5-293-3477', '', 'https://sites.google.com/view/estudio-cabrera-pita-abogados/inicio', 'Ciudadela California Calle Chone, y y Junín Esquina, 130105 Portoviejo, Ecuador', 'Portoviejo', 'Ecuador', '5.0', '77', 'ChIJczWYTG3zK5ARGJZUABzWu_g', 'https://www.google.com/maps/search/Estudio%20Jur%C3%ADdico%20Cabrera%20Pita%20%26Abogados%20Portoviejo', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkTdXD2KuGU1o4xiWnol7W3jYYUDd6UdyoYrnBHMltR2u3z8XAPCQMmd9m3luBSteC6fmK5wfbn2fdHFailGrlLlxtJXLFgCEtKKRBpKxh8c808VatGjnxFNiu0mVJ8nxOKgIHyKQ=w1000-h1000-c-n', '', '[]', 'scraped', '', '', '', '{}', '', '') ON CONFLICT (slug) DO NOTHING;

INSERT INTO leads (slug, business_name, business_type, category, description_short, phone, email, website, address, city, country, rating, reviews_count, place_id, google_url, logo_url, hero_url, images, status, notes, contact_method, contact_date, brief_data, problem, problem_key) VALUES ('estudio-jurídico-chicachang', 'Estudio Jurídico ChicaChang', 'Bufete', '', '', '+593 5-265-7114', '', '', 'Calle. Ricaurte entre Av. América y calle Cesar Chavez., frente al Parque de la Madre, 1er piso alto, Edif. Chang, Portoviejo - Manabí, 130103 Portoviejo, Ecuador', 'Portoviejo', 'Ecuador', '4.7', '11', 'ChIJjc0lFkyNK5ARWTihbu7TcE0', 'https://www.google.com/maps/search/Estudio%20Jur%C3%ADdico%20ChicaChang%20Portoviejo', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnizoMN_1oR9htKvA-w7wFP5QclDUp9lCqmbce0gpgRUu1XZaO1xVGDGE-Sel2xWq4_u-uIRbB8JWuVWWDkYIt0lxHccD0KGUHH9N2AB8_HpfL4YXQ5K0veyXJ5NY1nA-MYzPL-=w1000-h1000-c-n', '', '[]', 'scraped', '', '', '', '{}', '', '') ON CONFLICT (slug) DO NOTHING;

INSERT INTO leads (slug, business_name, business_type, category, description_short, phone, email, website, address, city, country, rating, reviews_count, place_id, google_url, logo_url, hero_url, images, status, notes, contact_method, contact_date, brief_data, problem, problem_key) VALUES ('villarroel-abogados', 'Villarroel Abogados', 'Abogado', '', '', '+593 99 981 3207', '', '', 'Edificio Manta Business Center Calle M2 y Calle, M3, Manta, Ecuador', 'Manta', 'Ecuador', '4.9', '56', 'ChIJ5XjUFJHhK5AReqw3nXAZVm4', 'https://www.google.com/maps/search/Villarroel%20Abogados%20Manta', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkQ2_b4CfblCqAscEndpeeaf_3m4dPRDj7euRR5082tPJckaOuiPi59vJ_09_TXQED9slPl5Zp9GBOwHWigybAWm4aFtJNCZtqz4E3f6o_FQ3X6HVj-K2wJKUvi9g7kIOcuPgHI=w1000-h1000-c-n', '', '[]', 'scraped', '', '', '', '{}', 'no tiene pagina web', 'no_web') ON CONFLICT (slug) DO NOTHING;

INSERT INTO leads (slug, business_name, business_type, category, description_short, phone, email, website, address, city, country, rating, reviews_count, place_id, google_url, logo_url, hero_url, images, status, notes, contact_method, contact_date, brief_data, problem, problem_key) VALUES ('vera-abogados', 'Vera & Abogados', 'Abogado', '', '', '+593 5-262-3333', '', 'http://www.veraiabogados.com/', 'Av. 2 entre calles 11 y 12 Edif. Bco. Pichicha, Piso 8, Of. 803 - 804, Manta, Ecuador', 'Manta', 'Ecuador', '5.0', '19', 'ChIJbVwqvjThK5AR4PwR1vFZ19c', 'https://www.google.com/maps/search/Vera%20%26%20Abogados%20Manta', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkUjDGcH5I0y04b5cp7KyHu6dV1HvTy0FCXW3WO77nArwZhFhkZBEdRdWoLVpS3ojzfcxzVZuSw-qMtCB4X4FuYThqY3f_GOC6ACt9nQgPSBhu1YVi57xthlhztQyouFVsfTDRG=w1000-h1000-c-n', '', '[]', 'done', '', '', '', '{}', '', '') ON CONFLICT (slug) DO NOTHING;

INSERT INTO leads (slug, business_name, business_type, category, description_short, phone, email, website, address, city, country, rating, reviews_count, place_id, google_url, logo_url, hero_url, images, status, notes, contact_method, contact_date, brief_data, problem, problem_key) VALUES ('cedeño-abogados', 'CEDEÑO ABOGADOS', 'Servicios legales', '', '', '+593 98 139 5634', '', '', 'C. 7 y Av. 11, Manta, Ecuador', 'Manta', 'Ecuador', '5.0', '1', 'ChIJY_BK6eHhK5ARFQjQf3TVdmM', 'https://www.google.com/maps/search/CEDE%C3%91O%20ABOGADOS%20Manta', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmmPJIdQIfJqlv6kYj-LXEmKKyDcn4bdNxDieNhTAMTP0cS3v8Ooe-M7zEl5aBKQmnNYH02UN2RchQ6IXzv_NbFX118d5GOGWEREMnzXJQWqkHFSajzr799liX-u4fDsGDHv-hZzENgjnlm=w1000-h1000-c-n', '', '[]', 'responded', '', '', '', '{}', '', '') ON CONFLICT (slug) DO NOTHING;

INSERT INTO leads (slug, business_name, business_type, category, description_short, phone, email, website, address, city, country, rating, reviews_count, place_id, google_url, logo_url, hero_url, images, status, notes, contact_method, contact_date, brief_data, problem, problem_key) VALUES ('molina-joza-law-firm', 'Molina Joza Law Firm', 'Abogado', '', '', '', '', 'https://molinajozafirm.com/', 'Edificio Mutualista Pichincha of. 3.1, C. 9 y Av. 4, 130802 Manta, Ecuador', 'Manta', 'Ecuador', '5.0', '4', 'ChIJgf3xX-jhK5AR75ITysq8Qvs', 'https://www.google.com/maps/search/Molina%20Joza%20Law%20Firm%20Manta', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmH33n_nI52h2DsQPG7KnvltB6ZPUXbdaOZBI8AeAdsObGW71m6mS9fa25wP_hDgdRREsPzmFl-hBBA4IZpZhHwamG1LWIL9fD7fnLqD68RNt8L4zNgN57SfH6hT-fiy9jwD30=w1000-h1000-c-n', '', '[]', 'rejected', '', '', '', '{}', '', '') ON CONFLICT (slug) DO NOTHING;

INSERT INTO leads (slug, business_name, business_type, category, description_short, phone, email, website, address, city, country, rating, reviews_count, place_id, google_url, logo_url, hero_url, images, status, notes, contact_method, contact_date, brief_data, problem, problem_key) VALUES ('dynamis-fortiori-s-a', 'DYNAMIS & FORTIORI S. A.', 'Oficinas de empresa', '', '', '+593 5-500-1545', '', 'http://www.dynamisfortiori.com/', 'CI y Cl. M 3 112, Manta, Ecuador', 'Manta', 'Ecuador', '5.0', '115', 'ChIJ9Uevpu_hK5AR08XU0MSNZYY', 'https://www.google.com/maps/search/DYNAMIS%20%26%20FORTIORI%20S.%20A.%20Manta', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmnjWNMVMz_RMk6vb3R3uYG91QOs2X3Z1egZkhlauZuZ0Y1773R4SV0Q71EMrNiAWNrhTacJ_mAilTtTGaE-izO-J1szpvPMSGEZH_-BuQg-ATNnLkNbpNmFszHrAT_JPwpBeE=w1000-h1000-c-n', '', '[]', 'brief_generated', '', '', '', '{}', '', '') ON CONFLICT (slug) DO NOTHING;

INSERT INTO leads (slug, business_name, business_type, category, description_short, phone, email, website, address, city, country, rating, reviews_count, place_id, google_url, logo_url, hero_url, images, status, notes, contact_method, contact_date, brief_data, problem, problem_key) VALUES ('guidotti-asociados', 'Guidotti & Asociados', 'Bufete', '', '', '+593 98 774 3357', '', '', '3758+3CW, C. M 2, Manta, Ecuador', 'Manta', 'Ecuador', '5.0', '1', 'ChIJA8N8_MPhK5AR_ENoUAbtoyk', 'https://www.google.com/maps/search/Guidotti%20%26%20Asociados%20Manta', 'https://streetviewpixels-pa.googleapis.com/v1/thumbnail?panoid=ivqXEhyyhSz548i4iPU9mA&cb_client=search.gws-prod.gps&w=80&h=92&yaw=293.15594&pitch=0&thumbfov=100', '', '[]', 'contacted', '', '', '', '{}', '', '') ON CONFLICT (slug) DO NOTHING;

INSERT INTO leads (slug, business_name, business_type, category, description_short, phone, email, website, address, city, country, rating, reviews_count, place_id, google_url, logo_url, hero_url, images, status, notes, contact_method, contact_date, brief_data, problem, problem_key) VALUES ('abogado-tulio-bravo-bermeo', 'ABOGADO TULIO BRAVO BERMEO', 'Oficina de Asuntos Jurídicos', '', '', '+593 96 960 1148', '', 'https://abtuliobravo.blogspot.com/', 'Av 35 y calle 9 Av 35, y y C. 9, 130740 Manta, Ecuador', 'Manta', 'Ecuador', '5.0', '11', 'ChIJNZsMIz6ZK5ARvSOuwMZ6XAk', 'https://www.google.com/maps/search/ABOGADO%20TULIO%20BRAVO%20BERMEO%20Manta', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWk2budhM8NgF8arKAVrF53Fq3ogAn70vaxM_zOQ5oBLVP5PgBSZh8ECKH-QAKMl_v1jHLjYBW1POYaCu_958NeQX-c8J3CaFEW1fA-QezFW4QlIuzwyANt0Sn2sov4g7aVyFn7r=w1000-h1000-c-n', '', '[]', 'contacted', '', '', '', '{}', 'no tiene página web', 'no_web') ON CONFLICT (slug) DO NOTHING;

INSERT INTO leads (slug, business_name, business_type, category, description_short, phone, email, website, address, city, country, rating, reviews_count, place_id, google_url, logo_url, hero_url, images, status, notes, contact_method, contact_date, brief_data, problem, problem_key) VALUES ('zamora-abogados', 'Zamora Abogados', 'Abogado penalista', '', '', '+593 98 694 9598', '', 'http://zamoraabogados.com.ec/', 'Calle 10 y Av. 7 y 8, 130213 Manta, Ecuador', 'Manta', 'Ecuador', '5.0', '4', 'ChIJVUW4UkPhK5ARtA6lgBWZNh4', 'https://www.google.com/maps/search/Zamora%20Abogados%20Manta', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWnRwiZ1z7Q_2BpWg9P96QI7Bib63JZNH3mPZAEN-cJKNvKVdVN2ZPu8SuhRVSrIi1o2lxFFKw3RoPUuq-25TfGIDM9YBQxttzGbnG6C4n__urRgyvkdeUOm_arp7P0yTCabLNGMLw=w1000-h1000-c-n', '', '[]', 'scraped', '', '', '', '{}', '', '') ON CONFLICT (slug) DO NOTHING;

INSERT INTO leads (slug, business_name, business_type, category, description_short, phone, email, website, address, city, country, rating, reviews_count, place_id, google_url, logo_url, hero_url, images, status, notes, contact_method, contact_date, brief_data, problem, problem_key) VALUES ('osm-estudio-jurídico-dr-oswaldo-segovia-medina', 'OSM Estudio Jurídico - Dr. Oswaldo Segovia Medina', 'Abogado', '', '', '+593 5-257-8034', '', 'http://www.osmestudiojuridico.com/', 'Via Manta - Montecristi, Manta, Ecuador', 'Manta', 'Ecuador', '5.0', '1', 'ChIJpcJH20_lK5ARn7UOolaJhDI', 'https://www.google.com/maps/search/OSM%20Estudio%20Jur%C3%ADdico%20-%20Dr.%20Oswaldo%20Segovia%20Medina%20Manta', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWkcy3Zg9_gsUbGQzHdUg5tiItD-vmPFTCnm0BaCJRKhZx4jQlhuDUBfnSknvOz7aw0FeFgOnAjR4ySqEoRsG5LDGya5WnDCJgMNIpWj7OhHtZ8Dsdx8SGZsan3psceg78wpwYot=w1000-h1000-c-n', '', '[]', 'scraped', '', '', '', '{}', '', '') ON CONFLICT (slug) DO NOTHING;

INSERT INTO leads (slug, business_name, business_type, category, description_short, phone, email, website, address, city, country, rating, reviews_count, place_id, google_url, logo_url, hero_url, images, status, notes, contact_method, contact_date, brief_data, problem, problem_key) VALUES ('ecuaassist-manta', 'EcuaAssist Manta', 'Abogado especialista en derecho de extranjería', '', '', '+593 99 011 1818', '', 'http://www.ecuaassist.com/', 'Calle 23 y Flavio Reyes, 090105 Manta, Ecuador', 'Manta', 'Ecuador', '4.5', '114', 'ChIJySL_QDrhK5ARGEGsTu1ORoY', 'https://www.google.com/maps/search/EcuaAssist%20Manta%20Manta', 'https://lh3.googleusercontent.com/gps-cs-s/AHRPTWmJ-k6BXxCHeihTfCgtGYAQ81GC6nYIOXQcARj61xkmftRJuiYWK6oooVstDGktTvJ2xYywy-NUBChAy0YdkKwpL5mTc6jnuxTqyPxVrnJzINYDEFH7EHv34j7Rqq5AGAPgfLpubA=w1000-h1000-c-n', '', '[]', 'scraped', '', '', '', '{}', '', '') ON CONFLICT (slug) DO NOTHING;

-- Total: 15 leads
